In [42]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/zomato-restaurant-dataset/enhanced_zomato_dataset_clean.csv

In [4]:
dataset = pd.read_csv("/kaggle/input/zomato-restaurant-dataset/enhanced_zomato_dataset_clean.csv")
dataset.head(5)

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining_Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,...,Is_Bestseller,Restaurant_Popularity,Avg_Rating_Restaurant,Avg_Price_Restaurant,Avg_Rating_Cuisine,Avg_Price_Cuisine,Avg_Rating_City,Avg_Price_City,Is_Highly_Rated,Is_Expensive
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NONE,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123657 entries, 0 to 123656
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Restaurant_Name        123657 non-null  object
 1   Dining_Rating          123657 non-null  float64
 2   Delivery_Rating        123657 non-null  float64
 3   Dining_Votes           123657 non-null  int64
 4   Delivery_Votes         123657 non-null  int64
 5   Cuisine                123657 non-null  object
 6   Place_Name             123657 non-null  object
 7   City                   123657 non-null  object
 8   Item_Name              123657 non-null  object
 9   Best_Seller            123657 non-null  object
 10  Votes                  123657 non-null  int64
 11  Prices                 123657 non-null  float64
 12  Average_Rating         123657 non-null  float64
 13  Total_Votes            123657 non-null  int64
 14  Price_per_Vote         123657 non-null  float64
 15  Log_Price              123657 non-null  float64
 16  Is_Bestseller          123657 non-null  int64
 17  Restaurant_Popularity  123657 non-null  int64
 18  Avg_Rating_Restaurant  123657 non-null  float64
 19  Avg_Price_Restaurant   123657 non-null  float64
 20  Avg_Rating_Cuisine     123657 non-null  float64
 21  Avg_Price_Cuisine      123657 non-null  float64
 22  Avg_Rating_City        123657 non-null  float64
 23  Avg_Price_City         123657 non-null  float64
 24  Is_Highly_Rated        123657 non-null  int64
 25  Is_Expensive           123657 non-null  int64
dtypes: float64(12), int64(8), object(6)
memory usage: 24.5+ MB

In [6]:
dataset.isnull().sum()

Restaurant_Name          0
Dining_Rating            0
Delivery_Rating          0
Dining_Votes             0
Delivery_Votes           0
Cuisine                  0
Place_Name               0
City                     0
Item_Name                0
Best_Seller              0
Votes                    0
Prices                   0
Average_Rating           0
Total_Votes              0
Price_per_Vote           0
Log_Price                0
Is_Bestseller            0
Restaurant_Popularity    0
Avg_Rating_Restaurant    0
Avg_Price_Restaurant     0
Avg_Rating_Cuisine       0
Avg_Price_Cuisine        0
Avg_Rating_City          0
Avg_Price_City           0
Is_Highly_Rated          0
Is_Expensive             0
dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder

label_cols = ["Restaurant_Name", "Cuisine", "City", "Item_Name", "Best_Seller","Place_Name"]

for col in label_cols:
    dataset[col] = LabelEncoder().fit_transform(dataset[col].astype(str))

In [22]:
dataset.head()

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining_Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,...,Is_Bestseller,Restaurant_Popularity,Avg_Rating_Restaurant,Avg_Price_Restaurant,Avg_Rating_Cuisine,Avg_Price_Cuisine,Avg_Rating_City,Avg_Price_City,Is_Highly_Rated,Is_Expensive
0,121,3.9,4.2,39,0,4,184,12,35037,0,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
1,121,3.9,4.2,39,0,4,184,12,2495,0,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
2,121,3.9,4.2,39,0,4,184,12,3155,12,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
3,121,3.9,4.2,39,0,4,184,12,54860,0,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
4,121,3.9,4.2,39,0,4,184,12,41067,10,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0

In [23]:
from sklearn.model_selection import train_test_split

x = dataset.drop(columns = ["Dining_Rating"])
y = dataset["Dining_Rating"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [28]:
from xgboost import XGBRegressor as XGB
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

model_xgb = XGB()
model_xgb.fit(x_train,y_train)
y_pred_xgb = model_xgb.predict(x_test)
print("MSE: ",mean_squared_error(y_test,y_pred_xgb))
print("R2 SCORE: ",r2_score(y_test,y_pred_xgb))
print("MAE: ",mean_absolute_error(y_test,y_pred_xgb))

MSE:  9.824092483311168e-08
R2 SCORE:  0.9999992021450141
MAE:  0.00021013889279340083

In [31]:
from lightgbm import LGBMRegressor as LGBM

model_lgbm = LGBM()
model_lgbm.fit(x_train,y_train)
y_pred_lgbm = model_lgbm.predict(x_test)
print("MSE: ",mean_squared_error(y_test,y_pred_lgbm))
print("R2 SCORE: ",r2_score(y_test,y_pred_lgbm))
print("MAE: ",mean_absolute_error(y_test,y_pred_lgbm))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011424 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3358
[LightGBM] [Info] Number of data points in the train set: 98925, number of used features: 24
[LightGBM] [Info] Start training from score 3.821979
MSE:  7.471456561527237e-06
R2 SCORE:  0.9999393212260673
MAE:  0.0019190679534436758

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaler = scaler.fit_transform(x_train)
x_test_scaler = scaler.transform(x_test)

model_keras = Sequential([
    Dense(128,activation = "relu",input_shape=(x_train_scaler.shape[1],)),
    Dropout(0.3),
    Dense(64,activation="relu"),
    Dropout(0.3),
    Dense(1)
])

model_keras.compile(optimizer = Adam(),loss = "mse",metrics = ["mae"])
history = model_keras.fit(
    x_train_scaler,y_train,
    validation_data = (x_test_scaler, y_test),
    epochs = 20,
    batch_size = 128,
    verbose = 1
)

Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

773/773 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 1.4606 - mae: 0.8689 - val_loss: 0.0466 - val_mae: 0.1696
Epoch 2/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.2727 - mae: 0.4133 - val_loss: 0.0140 - val_mae: 0.0897
Epoch 3/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1821 - mae: 0.3369 - val_loss: 0.0042 - val_mae: 0.0495
Epoch 4/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1348 - mae: 0.2898 - val_loss: 0.0027 - val_mae: 0.0390
Epoch 5/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.1069 - mae: 0.2589 - val_loss: 0.0023 - val_mae: 0.0393
Epoch 6/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0838 - mae: 0.2277 - val_loss: 0.0043 - val_mae: 0.0594
Epoch 7/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0623 - mae: 0.1969 - val_loss: 7.6053e-04 - val_mae: 0.0184
Epoch 8/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0454 - mae: 0.1678 - val_loss: 0.0015 - val_mae: 0.0294
Epoch 9/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0307 - mae: 0.1374 - val_loss: 8.8992e-04 - val_mae: 0.0188
Epoch 10/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0197 - mae: 0.1092 - val_loss: 0.0014 - val_mae: 0.0209
Epoch 11/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0121 - mae: 0.0847 - val_loss: 0.0027 - val_mae: 0.0294
Epoch 12/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0073 - mae: 0.0646 - val_loss: 0.0030 - val_mae: 0.0259
Epoch 13/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0048 - mae: 0.0508 - val_loss: 0.0050 - val_mae: 0.0367
Epoch 14/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0038 - mae: 0.0434 - val_loss: 0.0038 - val_mae: 0.0300
Epoch 15/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0033 - mae: 0.0393 - val_loss: 0.0028 - val_mae: 0.0291
Epoch 16/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0031 - mae: 0.0371 - val_loss: 0.0021 - val_mae: 0.0231
Epoch 17/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0029 - mae: 0.0351 - val_loss: 0.0020 - val_mae: 0.0259
Epoch 18/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0028 - mae: 0.0344 - val_loss: 0.0026 - val_mae: 0.0255
Epoch 19/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0028 - mae: 0.0339 - val_loss: 0.0021 - val_mae: 0.0244
Epoch 20/20
773/773 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.0026 - mae: 0.0331 - val_loss: 0.0017 - val_mae: 0.0235

In [40]:
y_pred_keras = model_keras.predict(x_test_scaler).flatten()
print("R2 SCORE: ",r2_score(y_test,y_pred_keras))
print("MSE: ",mean_squared_error(y_test,y_pred_keras))
print("MAE: ",mean_absolute_error(y_test,y_pred_keras))

773/773 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
R2 SCORE:  0.9857921242610077
MSE:  0.0017494342672994248
MAE:  0.02354206131767034